[workspace]
resolver = "2"

members = [
    "bevy-strolle",
    "strolle",
    "strolle-raytracer",
    "strolle-raytracer-models",
    "strolle-renderer",
    "strolle-renderer-models",
    "strolle-shader-builder",
]
