[workspace]
resolver = "2"

members = [
    "bevy-strolle",
    "strolle",
    "strolle-models",
    "strolle-printing-pass",
    "strolle-shader-builder",
    "strolle-shading-pass",
    "strolle-tracing-pass",
]

[patch."crates-io"]
# TODO https://github.com/gfx-rs/naga/pull/2199
naga = { git = "https://github.com/Patryk27/naga", branch = "spirv_binding_arrays" }
