[workspace]
resolver = "2"

members = [
    "bevy-strolle",
    "strolle",
    "strolle-models",
    "strolle-pass-drawing",
    "strolle-pass-ray-shading",
    "strolle-pass-ray-tracing",
    "strolle-shader-builder",
]

# TODO newest naga contains https://github.com/gfx-rs/naga/pull/2199, but it's
#      also backwards-incompatible with wgpu 0.14, so in here we've got some
#      trickery to make them work together
[patch."crates-io"]
naga = { git = "https://github.com/Patryk27/naga", branch = "strolle" }
wgpu = { git = "https://github.com/Patryk27/wgpu", branch = "strolle" }
