[workspace]
resolver = "2"

members = [
    "bevy-strolle",
    "strolle",
    "strolle-materializer",
    "strolle-models",
    "strolle-printer",
    "strolle-shader-builder",
    "strolle-tracer",
]
