[package]
name = "strolle-renderer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
# Workspace
strolle-renderer-models = { path = "../strolle-renderer-models" }

# Crates.io
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", features = ["glam"] }
