[package]
name = "strolle-shaders"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std.workspace = true
strolle-gpu = { path = "../strolle-gpu" }
