[package]
name = "strolle-shaders"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
# Workspace
strolle-gpu = { path = "../strolle-gpu" }

# Crates.io
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu" }
